feat: write atkeys to file
atsign-foundation/at_c pull request #428
Opened 2024-10-15 15:18 UTC by JeremyTubongbanua

closes #415 

**- What I did**
- Work in progress

**- How I did it**

**- How to verify it**

**- Description for the changelog**
feat: write atkeys to file

2024-10-16 21:43 UTC, srieteja commented
@JeremyTubongbanua apkamSymmetricKey is now a part of the atKeys file, since implementation of APKAM. Could you please add impl to write that into the keys file too. Support for APKAMSymmetricKey is still not integrated into the at_c client. It's currently in this PR https://github.com/atsign-foundation/at_c/pull/412, could you please cherry pick these commits into this branch.

2024-10-16 21:45 UTC, srieteja requested changes
See earlier comment reg APKAMSymmetricKey

2024-10-18 19:59 UTC, XavierChanth approved these changes

2024-10-18 20:00 UTC, XavierChanth requested changes
Address the tests

2024-10-21 13:16 UTC, xavierchanth approved these changes

2024-10-21 20:30 UTC, srieteja approved these changes

2024-10-22 12:28 UTC, merged